import { Amplify } from "aws-amplify";
// Attempt to load Amplify outputs generated by `amplify pull` (Gen 2) or leave empty
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the file may be an empty placeholder until Amplify is set up
import outputs from "../../amplify_outputs.json";

// Ensure Amplify is configured exactly once for both server and client runtimes
Amplify.configure(outputs ?? {}, { ssr: true });

export {};