"use client";

import { Amplify, type ResourcesConfig } from "aws-amplify";
// Import the outputs generated by Amplify Hosting / Gen 2. A placeholder file
// is included in the repo to enable local dev. In your Amplify environment,
// this file will be replaced/augmented automatically during build.
import outputs from "../../amplify_outputs.json";

Amplify.configure(outputs as ResourcesConfig);